<?php

namespace AppBundle\Repository;

/**
 * Reading_notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reading_notificationRepository extends \Doctrine\ORM\EntityRepository
{
}
