<?php

namespace AppBundle\Repository;

/**
 * Reading_notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reading_notificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReadLinkNotif($notificationId, $notifiedUserId)
    {
        $query = $this->createQueryBuilder('r')
        ->select('r')
        ->where('r.notification = ?1')
        ->andWhere('r.notifiedUser = ?2')
        ->setParameter(1, $notificationId)
        ->setParameter(2, $notifiedUserId)
        ->getQuery()->getResult();
        return $query;
    }
}
