<?php

namespace AppBundle\Repository;

/**
 * SpecialtyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtyRepository extends \Doctrine\ORM\EntityRepository
{
}
